# Generated by Django 4.2.6 on 2023-10-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceosupdate',
            name='year_started',
            field=models.IntegerField(null=True),
        ),
    ]
